config/routes.rb
Rails.application.routes.draw do
  resources :projects do
    resources :roles, except: [:show]
  end
  resources :users, only: [:new, :create]
  resources :sessions, only: [:create, :destroy]
  
  root to: 'home#welcome'
  get "registration", to: "users#new", as: "registration"
  get "login", to: 'sessions#new', as: "login"
  get "logout", to: 'sessions#destroy', as: "logout"
  get 'dashboards/dashboard', to: 'dashboards#dashboard', as: "dashboard"
  get '/auth/:provider/callback' => 'sessions#omniauth'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
    has_many :roles, :dependent => :destroy
    has_many :users, through: :roles, :dependent => :destroy

    accepts_nested_attributes_for :roles, reject_if: :all_blank

    validates :name, presence: true, uniqueness: true
    validates :location, presence: true, uniqueness: true
    validates :start_date, presence: true
    validates :end_date, presence: true

    scope :active, -> { where("? BETWEEN start_date AND end_date", Date.today)} 
    scope :past, -> { where('end_date < ?', Date.today)} 
    scope :future, -> { where('start_date > ?', Date.today)}
end

app/models/role.rb
class Role < ApplicationRecord
    belongs_to :user
    belongs_to :project

    validates :title, presence: true
    validates_uniqueness_of :user_id, :scope => :project_id

    scope :alphabetical, -> { Role.joins(:user).order(:name)}
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    enum role: [:employee, :admin]
    has_many :roles, :dependent => :destroy
    has_many :projects, through: :roles, :dependent => :destroy

    validates :email, presence: true, uniqueness: true

    def self.from_omniauth(response)
        User.find_or_create_by(uid: response[:uid], provider: response[:provider]) do |u|
            u.name = response[:info][:name]
            u.email = response[:info][:email]
            u.password = SecureRandom.hex(15)
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user

    private

    def current_user
        if session[:user_id]
            @current_user ||= User.find(session[:user_id])
        else
            @current_user = nil
        end
    end

    def authenticate_admin!
        if !current_user.admin?
            flash[:alert] = "You do not have access to this page (Admin Only)."
            redirect_to dashboard_path
        end
    end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :require_login

  def dashboard
    if current_user.admin?
      @projects = Project.all
      @active_projects = Project.active
      @future_projects = Project.future
      @past_projects = Project.past
    else
      @projects = current_user.projects
      @active_projects = current_user.projects.active
      @future_projects = current_user.projects.future
      @past_projects = current_user.projects.past
    end
  end

  private

  def require_login
    unless current_user
    flash[:alert] = "You must be logged in to access this section."
    redirect_to login_path
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def welcome
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    before_action :authenticate_admin!, except: :show
    before_action :set_project, except: [:new, :create]

    def new
        @project = Project.new
        5.times {@project.roles.build}
    end

    def create
        @project = Project.new(project_params)
        if @project.save
          flash[:notice] = "Your project has been created."
          redirect_to dashboard_path
        else 
          5.times {@project.roles.build}
          render :new
        end
    end

    def edit 
    end

    def update
        if @project.update(project_params)
          flash[:notice]= "Your project has been updated."
          redirect_to dashboard_path
        else
          flash[:alert]= "Project update was unsuccessful."
          render :edit
        end
    end

    def destroy
        if @project.destroy
          flash[:notice] = "Your project was successfully deleted."
          redirect_to dashboard_path
        else
          flash[:alert] = "Project deletion was unsuccessful."
          redirect_to dashboard_path
        end
    end

    def show 
    end

    private

    def set_project
        @project = Project.find(params[:id])
      end

    def project_params
        params.require(:project).permit(
            :name,
            :location,
            :start_date,
            :end_date,
            :description,
            :revenue_estimate, 
            :cost_estimate,
            user_ids: [],
            roles_attributes: [:id, :user_id, :title]
          )
    end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
    before_action :set_project, only: [:new, :index, :edit]
    before_action :set_role, only: [:edit, :update, :destroy]
    before_action :authenticate_admin!, except: :index

    def new
        @role = Role.new
    end

    def create
        @role = Role.new(role_params)
        @role.project_id = params[:project_id]
        if @role.save
            flash[:notice] = 'Your teammate has been added.'
            redirect_to project_roles_path(params[:project_id])
        else
            flash[:alert] = 'Teammate creation was unsuccessful.'  
            render :new
        end
    end

    def index
    end

    def edit
    end

    def update
        if @role.update(title: params[:role][:title])
            flash[:notice] = "Your role title has been updated."
            redirect_to project_roles_path(params[:project_id])
        else
            flash[:alert] = "Title update was unsuccessful."
            render :edit
        end
    end

    def destroy
        if @role.destroy
            flash[:notice] = "Your teammate has been removed."
            redirect_to project_roles_path(params[:project_id])
        else
            flash[:alert] = "Teammate removal was unsuccessful."
            render :index
        end
    end

    private

    def role_params
        params.require(:role).permit(
            :title,
            :user_id
          )
    end

    def set_project
        @project = Project.find(params[:project_id])
    end

    def set_role
        @role = Role.find(params[:id])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to dashboard_path, notice: "You are logged in!"
    else
      if user == nil
        flash[:alert] = "Invalid email. Please try again."
      else
        flash[:alert] = "Invalid password. Please try again."
      end
      render :new
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end

  def omniauth
    user = User.from_omniauth(request.env['omniauth.auth'])
    if user.valid?
      session[:user_id] = user.id
      redirect_to dashboard_path
    else
      redirect_to '/login'
    end
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
    def new
        @team = Team.new
        @project = Project.find(params[:project_id])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to dashboard_path
        else
            render :new
        end
    end

    private

    def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def flash_message
        if flash[:notice] || flash[:alert] 
            content_tag(:div, flash[:notice] || flash[:alert], class: "alert alert-#{flash[:notice] ? 'success' : 'danger'} alert dismissable fade show m-0", role:'alert')
        end   
    end
end

app/views/dashboards/_admin_dash.html.erb
<div class="container p-0">
    <div class="d-flex justify-content-end">
        <%= link_to "Add a New Project", new_project_path, class: "btn btn-success" %>
    </div>
</div>
<div class="container dash p-3 my-3">
    <div class="row">
        <div class="col-md-4 col-sm-6">
            <h3>Active Projects:</h3>
            <% if @active_projects.any? %>
            <% @active_projects.each do |project| %>
                <div class="my-3">
                    <%= link_to project.name, project_path(project), class: "btn btn-secondary" %>
                </div>
            <% end %>
            <% else %>
                <h5>No active projects, yet.</h5>
            <% end %>
        </div>
        <div class="col-md-4 col-sm-6">
            <h3>Past Projects:</h3>
            <% if @past_projects.any? %>
            <% @past_projects.each do |project| %>
                <div class="my-3">
                    <%= link_to project.name, project_path(project), class: "btn btn-secondary" %>
                </div>
            <% end %>
            <% else %>
                <h5>No past projects, yet.</h5>
            <% end %>
        </div>
        <div class="col-md-4 col-sm-6">
            <h3>Future Projects:</h3>
            <% if @future_projects.any? %>
                <% @future_projects.each do |project| %>
                    <div class="my-3">
                        <%= link_to project.name, project_path(project), class: "btn btn-secondary" %>
                    </div>
                <% end %>
            <% else %>
                <h5>No future projects, yet.</h5>
            <% end %>
        </div>
    </div>
</div>

app/views/dashboards/_employee_dash.html.erb
<div class="container dash p-3">
    <div class="row">
    <div class="col-md-4 col-sm-6">
        <h3>Active Projects:</h3>
        <% if @active_projects.any? %>
        <% @active_projects.each do |project| %>
            <div class="my-3">
                <%= link_to project.name, project_path(project), class: "btn btn-secondary" %>
            </div>
        <% end %>
        <% else %>
            <h5>No active projects, yet.</h5>
        <% end %>
    </div>
    <div class="col-md-4 col-sm-6">
        <h3>Past Projects:</h3>
        <% if @past_projects.any? %>
        <% @past_projects.each do |project| %>
            <div class="my-3">
                <%= link_to project.name, project_path(project), class: "btn btn-secondary" %>
            </div>
        <% end %>
        <% else %>
            <h5>No past projects, yet.</h5>
        <% end %>
    </div>
    <div class="col-md-4 col-sm-6">
        <h3>Future Projects:</h3>
        <% if @future_projects.any? %>
            <% @future_projects.each do |project| %>
                <div class="my-3">
                    <%= link_to project.name, project_path(project), class: "btn btn-secondary" %>
                </div>
            <% end %>
        <% else %>
            <h5>No future projects, yet.</h5>
        <% end %>
        </div>
    </div>
</div>

app/views/dashboards/dashboard.html.erb
<div class="container">
    <div class="row my-5">
        <h3>Hi, <%= current_user.name %> </h3>
        <h5>This is your dashboard.</h5>
    </div>
</div>
<div class="my-5 p-3">
    <% if current_user.admin? %>
        <%= render 'admin_dash' %>
    <% else %>
        <%= render 'employee_dash' %>
    <% end %>
</div>

app/views/home/welcome.html.erb
<div>
    <div class="row">
        <div class="col"></div>
        <div class="col"></div>
        <div class="col-sm">
            <div class="card my-3" id="welcome-card">
                <div class="card-body">
                    <h5 class="card-title">Welcome to Paragon Painting.</h5>
                    <p class="card-text">New users must register for their account. Registered users can login below.</p>
                    <%= link_to "Register here!", registration_path, class: "btn btn-outline-primary" %>
                    <%= link_to "Login",login_path, class: "btn btn-primary" %>  
                </div>
            </div>
        </div>
    </div> 
</div>

app/views/layouts/_errors.html.erb
<% if record.errors.any? %>
    <ul class="errors">
        <% record.errors.each do |error| %>
            <li><%= error.full_message %></li>
        <% end %>
    </ul>
<% end %>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous" />
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <title>Paragon Painting & Waterproofing</title>
  </head>
  <body>
  <% if params[:controller] == "home" %>
  <%= image_tag('background.png', class: 'home') %>
  <% else %>
  <%= image_tag('user_background.png', class: 'user-background') %>
  <% end %>
    <%= flash_message %>
    <% if current_user %>
      <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item mx-3">
                  <%= link_to "Dashboard", dashboard_path, class: "btn btn-primary" %>
                </li>
                <li class="nav-item">
                  <%= link_to "Logout", logout_path, class: "btn btn-primary" %>
                </li>
              </ul>
            </div>
        </nav>
      </header>
    <% else %>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
    <%= link_to "Home", root_path, class: "btn btn-primary" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      </ul>
    </div>
  </div>
</nav>
    <% end %>
    
    <div class="wrapper">

        <%= yield %>

      <footer class="branding">
        <small>&copy; 2021 <strong>Paragon Painting & Waterproofing</strong></small>
      </footer>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
    <!--[if lt IE 7]>
      <script src="//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.2/CFInstall.min.js"></script>
      <script>window.attachEvent("onload",function(){CFInstall.check({mode:"overlay"})})</script>
    <![endif]-->
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with model: @project do |f| %>
    <%= render partial: "/layouts/errors", locals: {record: @project} %>
    <div class="mb-3">
      <%= f.label :name, "Name:", class: "form-label" %><br>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= f.label :location, "Location:", class: "form-label" %><br>
      <%= f.text_field :location, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= f.label :description, "Description:", class: "form-label" %><br>
      <%= f.text_field :description, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= f.label :start_date, "Start Date:", class: "form-label" %><br>
      <%= f.date_field :start_date,  class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= f.label :end_date, "End Date:", class: "form-label" %><br>
      <%= f.date_field :end_date, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= f.label :revenue_estimate, "Revenue Estimate:", step: 0.01, min: 0, class: "form-label" %><br>
      <%= f.number_field :revenue_estimate, class: "form-control" %>
    </div>
    <div class="mb-3">
    <%= f.label :cost_estimate, "Cost Estimate:", step: 0.01, min: 0, class: "form-label" %><br>
    <%= f.number_field :cost_estimate, class: "form-control" %>
  </div>

    <h3 class="text-center">Add Teammates</h3>
    <p class="text-center">Fields may be left blank.</p>
    <%= f.fields_for :roles do |r| %>
      <div class="mb-3">
          <%= r.label :user_id, "Name:", class: "form-label" %>
          <%= r.select(:user_id, User.all.collect {|u| [u.name, u.id]}, {prompt: 'Select Person'}, class: "form-control") %>
      </div>
      <div class="mb-3">
          <%= r.label :title, "Title:", class: "form-label" %>
          <%= r.text_field :title, class: "form-control" %>
      </div>
      <% end %><br>
    <%= f.submit "Create Project!", class: "btn btn-success my-3" %>
  <% end %>

app/views/projects/edit.html.erb
<div class="container">
    <div class="row">
        <div class="col-6 col-xs-12 mx-auto"> 
            <h3 class="text-center">Edit <%= @project.name %></h3>
            <%= render 'form' %>
        </div>
    </div>
</div>

app/views/projects/new.html.erb
<div class="container">
    <div class="row">
        <div class="col-6 col-xs-12 mx-auto"> 
            <h3 class="text-center">Create a New Project</h3>
            <%= render 'form' %>
        </div>
    </div>
</div>

app/views/projects/show.html.erb
<h1 class="text-center"><%= @project.name %></h1>
<div class="container">
    <div class="row">
        <div class="col-sm-12 col-md-4">
            <h2 class="text center">Project Details</h2>
            <ul>
                <li>Location: <%= @project.location %></li>
                <li>Start Date: <%= @project.start_date %></li>
                <li>End Date: <%= @project.end_date %></li>
                <li>Description: <%= @project.description %></li>
                <% if current_user.admin? %>
                    <li>Revenue Estimate: $<%= @project.revenue_estimate %></li>
                    <li>Cost Estimate: $<%= @project.cost_estimate %></li>
                <% end %>
            </ul>
        </div>
        <div class="col-sm-12 offset-md-4 col-md-4">
            <h2 class="text center">Project Teammates</h2>
            <%= link_to "See Project Team", project_roles_path(@project), class: "btn btn-success btn-lg w-auto m-3" %>
        </div>
    </div>
</div>

<% if current_user.admin? %>
    <div class="row flex-column align-items-center bg-light p-4">
    <h3 class="text-center"> Admin Controls </h3>
        <%= link_to "Edit #{@project.name}", edit_project_path(@project), class: "btn btn-warning btn-lg w-auto" %>
        <div class="border border-danger p-4 my-3 w-auto text-center">
            <h3>Danger Zone: Action Can't Be Undone!</h3>
            <%= button_to "Delete #{@project.name}", project_path(@project), method: :delete, class: "btn btn-danger btn-lg", data: { Confirm: 'Are you sure?' } %>
        </div>
    </div>
<% end %>

app/views/roles/edit.html.erb
<div class="container">
    <div class="row">
        <div class="col-6 mx-auto">
            <h3>Edit <%= @role.title %></h3>
            <%= form_for [@project, @role] do |f| %>
                <%= render partial: "layouts/errors", locals: {record: @role} %>
                <div class="mb-3">
                <%= f.select(:user_id, User.where.not(id: @project.users).collect {|u| [u.name, u.id]}, {prompt: 'Select Person'}, class: "form-control" ) %>
                </div>
                <div class="mb-3">
                    <%= f.label :title, "Title:", class: "form-label" %>
                    <%= f.text_field :title, class: "form-control" %>
                </div>
                <div class="text-center">
                    <%= f.submit "Edit Team Role", class: "btn btn-warning" %>
                </div>
              <% end %>
        </div>
    </div>
</div>

app/views/roles/index.html.erb
<div class="container">
    <div class="row">
        <div class="col-6 col-sm-12 mx-auto">
            <h3 class="text-center">Teammates for <%= @project.name %>:</h3>
            <%= link_to "Return to #{@project.name}", project_path(@project), class: "btn btn-primary mb-5" %>
            <% if @project.roles.any? %>
                <ul>
                    <% @project.roles.alphabetical.each do |role| %>
                        <li class="my-3"><%= role.user.name %>
                            <span>(<%= role.title %>)</span>
                            <% if current_user.admin? %>
                                <div class="d-flex">
                                    <%= link_to "Edit Teammate Title", edit_project_role_path(@project, role), class: "btn btn-warning" %>
                                    <%= button_to "Remove Teammate", project_role_path(@project, role), method: :delete, class: "btn btn-danger mx-3", data: { Confirm: 'Are you sure?' } %>
                                </div>
                            <% end %>
                        </li>
                    <% end %>
                </ul>
            <% else %>
                <h5 class="text-center">No teammates assigned to the <%= @project.name %> project.</h5>
            <% end %>
            <% if current_user.admin? %>
                <div class="text-center my-3">
                    <%= link_to "Add a Teammate", new_project_role_path(@project), class: "btn btn-success my-5" %>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/roles/new.html.erb
<div class="container">
    <div class="row">
        <div class="col-6 mx-auto">
            <h3>Add Teammate to <%= @project.name %> Project:</h3>
            <%= form_for [@project, @role] do |f| %>
                <%= render partial: "layouts/errors", locals: {record: @role} %>
                <div class="mb-3">
                <p>Select the Team Member:</p>
                <%= f.select(:user_id, User.where.not(id: @project.users).collect {|u| [u.name, u.id]}, {prompt: 'Select Person'}, class: "form-control" ) %>
                </div>
                <div class="mb-3">
                    <%= f.label :title, "Title:", class: "form-label" %>
                    <%= f.text_field :title, class: "form-control" %>
                </div>
                <div class="text-center">
                    <%= f.submit "Add Teammate", class: "btn btn-success" %>
                </div>
              <% end %>
        </div>
    </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-6 col-xs-12 mx-auto">
      <h1>New member? Register here.</h1>

      <%= form_with model: @user do |f| %>
        <%= render partial: "/layouts/errors", locals: {record: @user} %>
        <div class="mb-3">
          <%= f.label :name, "Name:", class: "form-label" %><br>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= f.label :email, "Email:", class: "form-label" %><br>
          <%= f.email_field :email, class: "form-control" %>
          <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
        </div>
        <div class="mb-3">
          <%= f.label :password, "Password:", class: "form-label" %><br>
          <%= f.password_field :password, class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= f.label :password_confirmation, "Password Confirmation:", class: "form-label" %><br>
          <%= f.password_field :password_confirmation, class: "form-control" %>
        </div>
        <div class="text-center mb-3">
          <%= f.submit "Join Paragon today!", class: "btn btn-secondary" %>
        </div>
      <% end %>
      <div class="text-center mb-3">
        <%= button_to "Log in with Google", '/auth/google_oauth2', class: "btn btn-primary"  %>
      </div>
    </div>
  </div>
</div>